# Generated by Django 5.0.13 on 2025-12-04 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservaciones', '0003_auto'),
    ]

    operations = [

    ]
